# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

u1=User.create(username:"langchao",password:"123456",admin:true)
u2=User.create(username:"customer1",password:"123",admin:false)
u3=User.create(username:"customer2",password:"456",admin:false)

game1=Game.create(name:"Marvel's Spider-Man: Miles Morales",price:49.99,image:"https://image.api.playstation.com/vulcan/ap/rnd/202008/1423/cZaoNGoCXpClHpljuPVPSUlw.jpg",game_type:"PS5")
Image.create(imgurl:"https://updatecrazy.com/wp-content/uploads/2021/08/Spider-man-Miles-Morales-Update-1.011-Patch-Notes-1.011.000.jpg",game_id:game1.id)
Image.create(imgurl:"https://mp1st.com/wp-content/uploads/2020/08/spiderman-miles.jpg",game_id:game1.id)
Image.create(imgurl:"https://i.ytimg.com/vi/ZSHhW7qpeNg/maxresdefault.jpg",game_id:game1.id)
Feature.create(description:'The Rise Of A New Hero – Miles Morales discovers explosive powers that set him apart from his mentor, Peter Parker. He learns to master his unique, bio-electric venom blast attacks and covert camouflage power alongside spectacular web-slinging acrobatics, gadgets and skills.',game_id:game1.id)
Feature.create(description:'A War For Power - A war for control of Marvel’s New York has broken out between a devious energy corporation and a high-tech criminal army. With his new home at the heart of the battle, Miles must learn the cost of becoming a hero and decide what he must sacrifice for the greater good.',game_id:game1.id)
Feature.create(description:'A Vibrant New Home - Traverse the snowy streets of his new, vibrant and bustling neighborhood as Miles searches for a sense of belonging. When the lines blur between his personal and crime-fighting lives, he discovers who he can trust, and what it feels like to truly be home.',game_id:game1.id)

game2=Game.create(name:"Horizon Forbidden West",price:69.99,image:"https://image.api.playstation.com/vulcan/ap/rnd/202107/3100/HO8vkO9pfXhwbHi5WHECQJdN.png",game_type:"PS5")
Image.create(imgurl:"https://images.pushsquare.com/7d18cd2fcdb7a/1280x720.jpg",game_id:game2.id)
Image.create(imgurl:"https://cdn.mos.cms.futurecdn.net/UwYhuHgLaRtpq9eXUBuwaM.jpg",game_id:game2.id)
Image.create(imgurl:"https://cdn.mos.cms.futurecdn.net/hWNZoezjgEezfRhYsvSW8V-1200-80.jpg",game_id:game2.id)
Feature.create(description:'Brave an expansive open world - Discover distant lands, new enemies, rich cultures and striking characters.',game_id:game2.id)
Feature.create(description:'A majestic frontier - Explore the lush forests, sunken cities and towering mountains of a far-future America.',game_id:game2.id)
Feature.create(description:'Confront new dangers - Engage in strategic battles against enormous machines and mounted human enemies by using weapons, gear and traps crafted from salvaged parts.',game_id:game2.id)
Feature.create(description:"Unravel startling mysteries - Uncover the secret behind Earth's imminent collapse and unlock a hidden chapter in the ancient past... one that will change Aloy forever.",game_id:game2.id)

game3=Game.create(name:"UNCHARTED™: Legacy of Thieves Collection",price:49.99,image:"https://image.api.playstation.com/vulcan/ap/rnd/202111/2000/gTUWTlvPHzxFJ2JAxtDyI2eS.png",game_type:"PS5")
Image.create(imgurl:"https://preview.redd.it/jh3pqrmoobi11.jpg?auto=webp&s=428dc4b81d19676c326166cc46c9d5d562c93de2",game_id:game3.id)
Image.create(imgurl:"http://farm8.staticflickr.com/7113/27077272765_ea99ce5a32_b.jpg",game_id:game3.id)
Image.create(imgurl:"https://cdn.akamai.steamstatic.com/steam/apps/1659420/ss_89a15e42a8ee05a8166467fe755c02a8754a195c.1920x1080.jpg?t=1638553142",game_id:game3.id)
Feature.create(description:'UNCHARTED: Legacy of Thieves Collection includes:',game_id:game3.id)
Feature.create(description:"UNCHARTED 4: A Thief's End and UNCHARTED: The Lost Legacy remastered for PS5.",game_id:game3.id)
Feature.create(description:'Play as Nathan Drake and Chloe Frazer in their own standalone adventures as they are forced to confront their pasts and forge their own legacies.',game_id:game3.id)
Feature.create(description:'Remote Play supported',game_id:game3.id)

game4=Game.create(name:"ELDEN RING",price:59.99,image:"https://phantom-marca.unidadeditorial.es/53108a6ebf13b3ee76bf9d31d24db9a0/resize/1200/f/jpg/assets/multimedia/imagenes/2022/02/24/16456590412309.jpg",game_type:"xbox")
Image.create(imgurl:"https://cdn.vox-cdn.com/thumbor/OXEDndGta4_l6JBoWOyC21_5bpg=/0x0:2560x1440/1200x675/filters:focal(1076x516:1484x924)/cdn.vox-cdn.com/uploads/chorus_image/image/70811935/20220428160001_1.0.jpg",game_id:game4.id)
Image.create(imgurl:"https://imageio.forbes.com/specials-images/imageserve/6272a7b0da7920e8b333ac05/Elden-Ring-armor/960x0.jpg?fit=bounds&format=jpg&width=960",game_id:game4.id)
Image.create(imgurl:"https://ewwnews.com/img/elden-ring-has-the-best-weapons-available-so-far-the-most-effective.jpeg",game_id:game4.id)
Feature.create(description:"A New Fantasy World - Journey through the Lands Between, a new fantasy world created by Hidetaka Miyazaki, creator of the influential DARK SOULS video game series, and George R. R. Martin, author of The New York Times best-selling fantasy series, A Song of Ice and Fire. Unravel the mysteries of the Elden Ring's power. Encounter adversaries with profound backgrounds, characters with their own unique motivations for helping or hindering your progress, and fearsome creatures.",game_id:game4.id)
Feature.create(description:'World Exploration in the Lands Between - ELDEN RING features vast fantastical landscapes and shadowy, complex dungeons that are connected seamlessly. Traverse the breathtaking world on foot or on horseback, alone or online with other players, and fully immerse yourself in the grassy plains, suffocating swamps, spiraling mountains, foreboding castles and other sites of grandeur on a scale never seen before in a FromSoftware title.',game_id:game4.id)
Feature.create(description:"Genre-Defining Gameplay - Create your character in FromSoftware's refi ned action-RPG and defi ne your playstyle by experimenting with a wide variety of weapons, magical abilities, and skills found throughout the world. Charge into battle, pick off enemies one-by-one using stealth, or even call upon allies for aid. Many options are at your disposal as you decide how to approach exploration and combat.",game_id:game4.id)
Feature.create(description:'NOTE - A free upgrade to the PlayStation 5 version will be available for players who purchase ELDEN RING on PlayStation 4, and SmartDelivery will be supported for Xbox One and Xbox Series X|S.',game_id:game4.id)

game5=Game.create(name:"Grand Theft Auto V",price:19.99,image:"https://compass-ssl.xbox.com/assets/a0/4f/a04f2744-74d9-4668-8263-e0261fbea869.jpg?n=GTA-V_GLP-Page-Hero-1084_1920x1080.jpg",game_type:"xbox")
Image.create(imgurl:"https://cdn.pocket-lint.com/r/s/970x/assets/images/123675-games-review-grand-theft-auto-v-review-image1-edv1ofamjx.jpg",game_id:game5.id)
Image.create(imgurl:"https://www.videogameschronicle.com/files/2019/08/grand-theft-auto-v-hotel.jpg",game_id:game5.id)
Image.create(imgurl:"https://i.ytimg.com/vi/vJWZo0yk_Ok/maxresdefault.jpg",game_id:game5.id)
Feature.create(description:'Play the genre-defining classics of the original Grand Theft Auto Trilogy: Grand Theft Auto III, Grand Theft Auto: Vice City and Grand Theft Auto: San Andreas updated for a new generation. ',game_id:game5.id)
Feature.create(description:'Featuring across-the-board enhancements including brilliant new lighting and environmental upgrades, high-resolution textures, increased draw distances, Grand Theft Auto V-style controls and targeting, and much more, these beloved worlds come to life with all new levels of detail.',game_id:game5.id)
Feature.create(description:'Developed by Rockstar Games, adapted by Grove Street Games.',game_id:game5.id)

game6=Game.create(name:"Red Dead Redemption",price:29.99,image:"https://image.api.playstation.com/cdn/UP1004/CUSA03041_00/Hpl5MtwQgOVF9vJqlfui6SDB5Jl4oBSq.png",game_type:"xbox")
Image.create(imgurl:"https://static0.gamerantimages.com/wordpress/wp-content/uploads/2021/05/red-dead-redemption-1-sized.jpg",game_id:game6.id)
Image.create(imgurl:"https://i.ytimg.com/vi/Linh71hKNEo/maxresdefault.jpg",game_id:game6.id)
Image.create(imgurl:"https://static01.nyt.com/images/2018/11/25/opinion/25SUDERMAN/25SUDERMAN-superJumbo.jpg",game_id:game6.id)
Feature.create(description:'America, 1899. The end of the wild west era has begun as lawmen hunt down the last remaining outlaw gangs. Those who will not surrender or succumb are killed.',game_id:game6.id)
Feature.create(description:'After a robbery goes badly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive.',game_id:game6.id)
Feature.create(description:'As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him. ',game_id:game6.id)
Feature.create(description:'From the creators of Grand Theft Auto V and Red Dead Redemption, Red Dead Redemption 2 is a sprawling tale of life in America at the dawn of the modern age.  ',game_id:game6.id)

game7=Game.create(name:"Nintendo Switch Sports",price:49.99,image:"https://assets.nintendo.com/image/upload/c_fill,f_auto,q_auto,w_1200/v1/ncom/en_US/games/switch/n/nintendo-switch-sports-switch/hero",game_type:"ns")
Image.create(imgurl:"https://assets-prd.ignimgs.com/2022/03/15/nintendo-switch-sports-screenshot-1647352669121.jpg",game_id:game7.id)
Image.create(imgurl:"https://media.cnn.com/api/v1/images/stellar/prod/220407163616-switch-nintendoswitchsports-screen-02.jpg?c=original",game_id:game7.id)
Image.create(imgurl:"https://cdn.pocket-lint.com/r/s/1200x630/assets/images/160701-games-review-hands-on-nintendo-switch-sports-preview-flailing-s-back-on-the-menu-image1-j5iqecul1u.jpg",game_id:game7.id)
Feature.create(description:'Swing, kick, spike, and bowl your way to victory in 6 sports',game_id:game7.id)
Feature.create(description:'Play Soccer, Volleyball, Bowling, Tennis, Badminton and Chambara (swordplay)',game_id:game7.id)
Feature.create(description:'Motion controls**** will get you moving and help turn your real-world actions into in-game movements',game_id:game7.id)
Feature.create(description:'Use the Leg Strap accessory to kick the ball in a Soccer Shoot-Out or, after a free update this summer***, in Soccer matches as well',game_id:game7.id)
Feature.create(description:'Play online** and challenge random opponents to earn in-game rewards like clothing, gear and much more or reach the Pro League',game_id:game7.id)
Feature.create(description:'Play with friends and family locally* or online**—in some sports, you and a friend can even team up on the same system to take on other teams online',game_id:game7.id)
Feature.create(description:'Golf is planned to be added via a free update this fall***',game_id:game7.id)

game8=Game.create(name:"Splatoon 3",price:59.99,image:"https://assets-prd.ignimgs.com/2022/04/22/splatoon-3-button-fin-1650649248602.jpg",game_type:"ns")
Image.create(imgurl:"https://images.nintendolife.com/89769500d7f36/splatoon-3.900x.jpg",game_id:game8.id)
Image.create(imgurl:"https://s.yimg.com/os/creatr-uploaded-images/2022-04/26808630-c242-11ec-957e-993decbec193",game_id:game8.id)
Image.create(imgurl:"https://www.vooks.net/img/2022/04/splatoon-key-art.jpg",game_id:game8.id)
Feature.create(description:'Ink it up with a new entry in the Splatoon series',game_id:game8.id)
Feature.create(description:'Discover the Splatlands, a new sun-soaked region with trendsetting inhabitants',game_id:game8.id)
Feature.create(description:'Experiment with new styles for Inklings and Octolings',game_id:game8.id)
Feature.create(description:'4v4 Turf Wars* are back, with new stages, new maneuvers, and new weapons',game_id:game8.id)
Feature.create(description:'Join Agent 3 in a fight against the unruly Octarians in story mode',game_id:game8.id)
Feature.create(description:'Take down giant Salmonid bosses together in the next wave of the Salmon Run* cooperative mode',game_id:game8.id)

game9=Game.create(name:"Zelda Breath of the Wild 2",price:59.99,image:"https://images.igdb.com/igdb/image/upload/t_cover_big_2x/co1uil.jpg",game_type:"ns")
Image.create(imgurl:"https://asset.vg247.com/screenshot-of-the-breath-of-the-wild-2-trailer-showing-villain.jpg/BROK/resize/1920x1920%3E/format/jpg/quality/80/screenshot-of-the-breath-of-the-wild-2-trailer-showing-villain.jpg",game_id:game9.id)
Image.create(imgurl:"https://images.nintendolife.com/b99a9b8ceb45a/breath-of-the-wild-2-link-and-zelda-with-a-torch.900x.jpg",game_id:game9.id)
Image.create(imgurl:"https://technozee.com/wp-content/uploads/2022/03/50.jpeg",game_id:game9.id)
Feature.create(description:'It features a torch-carrying Link and Zelda traversing a dark dungeon beneath Hyrule (no big surprise there).',game_id:game9.id)
review1=Review.create(comment:"very good game" , rating:5,game_id:game7.id, user_id:u1.id)

puts "seeding done"